.

diff --git a/.github/workflows/update_satatic_pages.yml b/.github/workflows/update_satatic_pages.yml
--- a/.github/workflows/update_satatic_pages.yml
+++ b/.github/workflows/update_satatic_pages.yml
@@ -25,13 +25,6 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
 
-      - name: Setup Java JDK
-        uses: actions/setup-java@v2.0.0
-        with:
-          java-version: 11
-          distribution: adopt
-          java-package: jre
-
       - name: Checkout site repository
         uses: actions/checkout@v2
         with: 
@@ -79,13 +72,19 @@ jobs:
             cut -c 4- -z | \
             xargs --null git commit -m "static media sync" || { if [[ "$?" -ne 123 ]] ; then false ; fi } 
 
+      - name: Resolve UID and GID
+        run: echo "UID_AND_GID=$(id -u):$(id -g)" >> $GITHUB_ENV
+          
       - name: Generate pages
-        run: |
-          docker run \
-            --rm \
-            --volume $PWD/..:/pages \
-            --user "$(id -u):$(id -g)" \
-            andriyg/pages-processor:0.0.8
+        uses: addnab/docker-run-action@v3
+        with:
+          image: andriyg/pages-processor:0.0.8
+          options: -v ${{ github.workspace }}:/pages --user "${{ env.UID_AND_GID }}"      
+
+      - name: Failure
+        run: set -e |
+          echo "Failure!"
+          false
 
       - name: Commit changes
         run: |
